version: '3.8'

services:
  mayan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mayan-custom
    ports:
      - "8111:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./mayan:/opt/mayan-edms/mayan  # optional if you want to live edit code

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: mayan
      POSTGRES_USER: mayan
      POSTGRES_PASSWORD: mayanpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: always

volumes:
  postgres_data:
